import { Nunito } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import Header from "./layouts/header";

const nunito = Nunito({ subsets: ["latin"], display: "optional" });

export const metadata = {
  title: "Learn next.JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
